services:
  signagelist:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - ./:/app
      - /app/node_modules
      - hugo_cache:/tmp/hugo_cache

volumes:
  hugo_cache:
